<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Question;
use App\Models\User;
use Carbon\Carbon;

class QuestionSeeder extends Seeder
{
    public function run(): void
    {
        // Get users (assuming you have users seeded)
        $users = User::all();

        if ($users->isEmpty()) {
            // If no users, create one first
            \App\Models\User::factory()->create([
                'name' => 'Test User',
                'email' => 'test@example.com',
            ]);
            $users = User::all();
        }

        $categories = [
            'academics',
            'admissions',
            'campus_life',
            'colleges',
            'entrance_exams',
            'events',
            'exams',
            'general',
            'programs',
            'scholarships',
        ];

        $questions = [
            // === ACADEMICS (3 questions) ===
            [
                'user_id' => $users->random()->id,
                'category' => 'academics',
                'title' => 'What is the grading system used in Nepali universities?',
                'body' => 'I\'m an international student planning to study in Nepal and I\'m curious about the grading system. Is it GPA-based or percentage-based? How does it compare to international grading systems?',
                'is_anonymous' => false,
                'is_draft' => false,
                'published_at' => now()->subDays(5),
                'views_count' => rand(50, 200),
                'replies_count' => rand(3, 10),
            ],
            [
                'user_id' => $users->random()->id,
                'category' => 'academics',
                'title' => 'How to improve academic writing skills?',
                'body' => 'As a college student, I struggle with academic writing. What resources or techniques do Nepali universities provide to help students improve their research paper writing skills?',
                'is_anonymous' => true,
                'is_draft' => false,
                'published_at' => now()->subDays(10),
                'views_count' => rand(100, 300),
                'replies_count' => rand(5, 15),
            ],
            [
                'user_id' => $users->random()->id,
                'category' => 'academics',
                'title' => 'Difference between thesis and dissertation?',
                'body' => 'I\'m confused about the difference between a thesis and dissertation in Nepali universities. When is each required and what are the specific requirements?',
                'is_anonymous' => false,
                'is_draft' => false,
                'published_at' => now()->subDays(3),
                'views_count' => rand(30, 150),
                'replies_count' => rand(2, 8),
            ],

            // === ADMISSIONS (4 questions) ===
            [
                'user_id' => $users->random()->id,
                'category' => 'admissions',
                'title' => 'When does TU BBA admission start?',
                'body' => 'I want to apply for BBA at Tribhuvan University. When does the admission process typically start and what documents are required?',
                'is_anonymous' => false,
                'is_draft' => false,
                'published_at' => now()->subDays(7),
                'views_count' => rand(150, 400),
                'replies_count' => rand(8, 20),
            ],
            [
                'user_id' => $users->random()->id,
                'category' => 'admissions',
                'title' => 'Entrance preparation tips for engineering',
                'body' => 'I\'m preparing for engineering entrance exams in Nepal. What subjects should I focus on and are there any good preparation books or coaching centers?',
                'is_anonymous' => false,
                'is_draft' => false,
                'published_at' => now()->subDays(15),
                'views_count' => rand(200, 500),
                'replies_count' => rand(10, 25),
            ],
            [
                'user_id' => $users->random()->id,
                'category' => 'admissions',
                'title' => 'Age limit for +2 admission?',
                'body' => 'Is there any age limit for admission to +2 (Grade 11) in Nepal? I\'m 20 years old and want to continue my studies.',
                'is_anonymous' => true,
                'is_draft' => false,
                'published_at' => now()->subDays(12),
                'views_count' => rand(80, 250),
                'replies_count' => rand(4, 12),
            ],
            [
                'user_id' => $users->random()->id,
                'category' => 'admissions',
                'title' => 'Late admission possibility in KU?',
                'body' => 'I missed the regular admission deadline for Kathmandu University. Do they have a late admission process or any alternative admission rounds?',
                'is_anonymous' => false,
                'is_draft' => false,
                'published_at' => now()->subDays(1),
                'views_count' => rand(40, 120),
                'replies_count' => rand(1, 5),
            ],

            // === CAMPUS_LIFE (3 questions) ===
            [
                'user_id' => $users->random()->id,
                'category' => 'campus_life',
                'title' => 'Best hostels near TU campus?',
                'body' => 'I\'m joining TU and looking for affordable and safe hostels near the campus. Any recommendations for good hostels with reasonable facilities?',
                'is_anonymous' => false,
                'is_draft' => false,
                'published_at' => now()->subDays(8),
                'views_count' => rand(120, 300),
                'replies_count' => rand(6, 18),
            ],
            [
                'user_id' => $users->random()->id,
                'category' => 'campus_life',
                'title' => 'Student clubs at Pokhara University',
                'body' => 'What kind of student clubs and extracurricular activities are available at Pokhara University? I\'m interested in joining some clubs.',
                'is_anonymous' => true,
                'is_draft' => false,
                'published_at' => now()->subDays(20),
                'views_count' => rand(60, 180),
                'replies_count' => rand(3, 9),
            ],
            [
                'user_id' => $users->random()->id,
                'category' => 'campus_life',
                'title' => 'Library facilities at NCIT',
                'body' => 'How good is the library at Nepal College of Information Technology? Do they have digital resources and study spaces?',
                'is_anonymous' => false,
                'is_draft' => false,
                'published_at' => now()->subDays(4),
                'views_count' => rand(70, 200),
                'replies_count' => rand(2, 7),
            ],

            // === COLLEGES (5 questions) ===
            [
                'user_id' => $users->random()->id,
                'category' => 'colleges',
                'title' => 'St. Xavier\'s vs Trinity College for BBA',
                'body' => 'I got admission in both St. Xavier\'s College and Trinity International College for BBA. Which one would be better in terms of faculty, placement, and campus life?',
                'is_anonymous' => false,
                'is_draft' => false,
                'published_at' => now()->subDays(6),
                'views_count' => rand(300, 600),
                'replies_count' => rand(15, 30),
            ],
            [
                'user_id' => $users->random()->id,
                'category' => 'colleges',
                'title' => 'Is KEC good for computer engineering?',
                'body' => 'I\'m considering Kathmandu Engineering College for computer engineering. How is their faculty, lab facilities, and placement record?',
                'is_anonymous' => true,
                'is_draft' => false,
                'published_at' => now()->subDays(25),
                'views_count' => rand(250, 500),
                'replies_count' => rand(12, 28),
            ],
            [
                'user_id' => $users->random()->id,
                'category' => 'colleges',
                'title' => 'Private vs government colleges in Nepal',
                'body' => 'What are the main differences between private and government colleges in Nepal in terms of fees, quality, and opportunities?',
                'is_anonymous' => false,
                'is_draft' => false,
                'published_at' => now()->subDays(30),
                'views_count' => rand(400, 800),
                'replies_count' => rand(20, 40),
            ],
            [
                'user_id' => $users->random()->id,
                'category' => 'colleges',
                'title' => 'Best medical colleges in Nepal',
                'body' => 'What are the top medical colleges in Nepal for MBBS? What are their admission criteria and approximate fees?',
                'is_anonymous' => false,
                'is_draft' => false,
                'published_at' => now()->subDays(18),
                'views_count' => rand(350, 700),
                'replies_count' => rand(18, 35),
            ],
            [
                'user_id' => $users->random()->id,
                'category' => 'colleges',
                'title' => 'College with best sports facilities',
                'body' => 'Which colleges in Kathmandu have the best sports facilities including gym, basketball court, and swimming pool?',
                'is_anonymous' => true,
                'is_draft' => false,
                'published_at' => now()->subDays(9),
                'views_count' => rand(100, 250),
                'replies_count' => rand(5, 12),
            ],

            // === ENTRANCE_EXAMS (4 questions) ===
            [
                'user_id' => $users->random()->id,
                'category' => 'entrance_exams',
                'title' => 'IOE entrance exam pattern',
                'body' => 'What is the exam pattern for IOE entrance exam? How many questions, marking scheme, and syllabus?',
                'is_anonymous' => false,
                'is_draft' => false,
                'published_at' => now()->subDays(14),
                'views_count' => rand(500, 1000),
                'replies_count' => rand(25, 50),
            ],
            [
                'user_id' => $users->random()->id,
                'category' => 'entrance_exams',
                'title' => 'Best books for medical entrance',
                'body' => 'Which books are recommended for preparation of medical entrance exams in Nepal? Any specific authors or publications?',
                'is_anonymous' => false,
                'is_draft' => false,
                'published_at' => now()->subDays(22),
                'views_count' => rand(400, 900),
                'replies_count' => rand(20, 45),
            ],
            [
                'user_id' => $users->random()->id,
                'category' => 'entrance_exams',
                'title' => 'KU entrance difficulty level',
                'body' => 'How difficult is Kathmandu University entrance exam compared to TU? What\'s the passing percentage usually?',
                'is_anonymous' => true,
                'is_draft' => false,
                'published_at' => now()->subDays(11),
                'views_count' => rand(300, 600),
                'replies_count' => rand(15, 30),
            ],
            [
                'user_id' => $users->random()->id,
                'category' => 'entrance_exams',
                'title' => 'Entrance coaching recommendations',
                'body' => 'Are entrance coaching classes really necessary? If yes, which coaching centers in Kathmandu are good for engineering entrance?',
                'is_anonymous' => false,
                'is_draft' => false,
                'published_at' => now()->subDays(28),
                'views_count' => rand(350, 700),
                'replies_count' => rand(18, 38),
            ],

            // === EVENTS (2 questions) ===
            [
                'user_id' => $users->random()->id,
                'category' => 'events',
                'title' => 'Upcoming college fests in Kathmandu',
                'body' => 'What are the upcoming college festivals or tech fests happening in Kathmandu this month? Any dates and venues?',
                'is_anonymous' => false,
                'is_draft' => false,
                'published_at' => now()->subDays(2),
                'views_count' => rand(80, 200),
                'replies_count' => rand(4, 10),
            ],
            [
                'user_id' => $users->random()->id,
                'category' => 'events',
                'title' => 'Career fair at St. Xavier\'s',
                'body' => 'When is the next career fair at St. Xavier\'s College? Which companies usually participate and is it open to students from other colleges?',
                'is_anonymous' => false,
                'is_draft' => false,
                'published_at' => now()->subDays(16),
                'views_count' => rand(120, 280),
                'replies_count' => rand(6, 15),
            ],

            // === EXAMS (5 questions) ===
            [
                'user_id' => $users->random()->id,
                'category' => 'exams',
                'title' => 'TU exam backlog system',
                'body' => 'How does the backlog system work in TU? If I fail in one subject, when can I reappear for the exam?',
                'is_anonymous' => false,
                'is_draft' => false,
                'published_at' => now()->subDays(19),
                'views_count' => rand(200, 450),
                'replies_count' => rand(10, 25),
            ],
            [
                'user_id' => $users->random()->id,
                'category' => 'exams',
                'title' => 'Practical exam preparation tips',
                'body' => 'How to prepare for practical exams in engineering? What do examiners usually look for in lab exams?',
                'is_anonymous' => true,
                'is_draft' => false,
                'published_at' => now()->subDays(13),
                'views_count' => rand(150, 350),
                'replies_count' => rand(8, 20),
            ],
            [
                'user_id' => $users->random()->id,
                'category' => 'exams',
                'title' => 'Exam cheating consequences in Nepal',
                'body' => 'What are the consequences if caught cheating in university exams in Nepal? Is there a permanent record?',
                'is_anonymous' => true,
                'is_draft' => false,
                'published_at' => now()->subDays(27),
                'views_count' => rand(250, 550),
                'replies_count' => rand(12, 28),
            ],
            [
                'user_id' => $users->random()->id,
                'category' => 'exams',
                'title' => 'Semester system vs annual system',
                'body' => 'Which is better: semester system or annual system in Nepali universities? What are the pros and cons of each?',
                'is_anonymous' => false,
                'is_draft' => false,
                'published_at' => now()->subDays(35),
                'views_count' => rand(300, 650),
                'replies_count' => rand(15, 32),
            ],
            [
                'user_id' => $users->random()->id,
                'category' => 'exams',
                'title' => 'External exam registration process',
                'body' => 'How to register as an external student for TU exams? What is the process and deadline?',
                'is_anonymous' => false,
                'is_draft' => false,
                'published_at' => now()->subDays(21),
                'views_count' => rand(180, 400),
                'replies_count' => rand(9, 22),
            ],

            // === GENERAL (3 questions) ===
            [
                'user_id' => $users->random()->id,
                'category' => 'general',
                'title' => 'Part-time jobs for students in Kathmandu',
                'body' => 'What are some good part-time job opportunities for college students in Kathmandu? Where to look for them?',
                'is_anonymous' => false,
                'is_draft' => false,
                'published_at' => now()->subDays(17),
                'views_count' => rand(400, 800),
                'replies_count' => rand(20, 40),
            ],
            [
                'user_id' => $users->random()->id,
                'category' => 'general',
                'title' => 'Student discount cards in Nepal',
                'body' => 'What kind of student discount cards are available in Nepal and where can I get one?',
                'is_anonymous' => false,
                'is_draft' => false,
                'published_at' => now()->subDays(24),
                'views_count' => rand(250, 500),
                'replies_count' => rand(12, 28),
            ],
            [
                'user_id' => $users->random()->id,
                'category' => 'general',
                'title' => 'Best time to study according to research',
                'body' => 'What is the best time to study according to scientific research? Morning or night study - which is more effective?',
                'is_anonymous' => true,
                'is_draft' => false,
                'published_at' => now()->subDays(29),
                'views_count' => rand(350, 700),
                'replies_count' => rand(18, 35),
            ],

            // === PROGRAMS (4 questions) ===
            [
                'user_id' => $users->random()->id,
                'category' => 'programs',
                'title' => 'BBA vs BBS - which is better?',
                'body' => 'What is the difference between BBA and BBS programs in Nepal? Which one has better career prospects?',
                'is_anonymous' => false,
                'is_draft' => false,
                'published_at' => now()->subDays(23),
                'views_count' => rand(300, 600),
                'replies_count' => rand(15, 30),
            ],
            [
                'user_id' => $users->random()->id,
                'category' => 'programs',
                'title' => 'Computer engineering vs IT',
                'body' => 'What is the main difference between computer engineering and information technology programs? Which has better scope in Nepal?',
                'is_anonymous' => false,
                'is_draft' => false,
                'published_at' => now()->subDays(31),
                'views_count' => rand(400, 750),
                'replies_count' => rand(20, 38),
            ],
            [
                'user_id' => $users->random()->id,
                'category' => 'programs',
                'title' => 'MBA specializations in Nepal',
                'body' => 'What specializations are available for MBA programs in Nepali universities? Which specialization is in demand?',
                'is_anonymous' => true,
                'is_draft' => false,
                'published_at' => now()->subDays(26),
                'views_count' => rand(280, 550),
                'replies_count' => rand(14, 29),
            ],
            [
                'user_id' => $users->random()->id,
                'category' => 'programs',
                'title' => 'New emerging courses in Nepal',
                'body' => 'What are some new and emerging courses in Nepali universities that have good future prospects?',
                'is_anonymous' => false,
                'is_draft' => false,
                'published_at' => now()->subDays(33),
                'views_count' => rand(220, 480),
                'replies_count' => rand(11, 26),
            ],

            // === SCHOLARSHIPS (2 questions) ===
            [
                'user_id' => $users->random()->id,
                'category' => 'scholarships',
                'title' => 'Government scholarships for +2',
                'body' => 'What government scholarships are available for +2 students in Nepal? How to apply and what are the criteria?',
                'is_anonymous' => false,
                'is_draft' => false,
                'published_at' => now()->subDays(32),
                'views_count' => rand(200, 450),
                'replies_count' => rand(10, 24),
            ],
            [
                'user_id' => $users->random()->id,
                'category' => 'scholarships',
                'title' => 'Full scholarships for engineering',
                'body' => 'Are there any full scholarships (100% tuition) available for engineering programs in private colleges?',
                'is_anonymous' => true,
                'is_draft' => false,
                'published_at' => now()->subDays(34),
                'views_count' => rand(180, 420),
                'replies_count' => rand(9, 21),
            ],
        ];

        foreach ($questions as $question) {
            Question::create($question);
        }
    }
}
